package ui

import (
	"fmt"
	"github.com/andygrunwald/go-jira"
	"github.com/fatih/color"
	"strings"
)

// IssueSummary creates a human-friendly summary of a Jira issue.
func IssueSummary(issue *jira.Issue, hasBranch bool) string {
	var colouredPriority string
	switch issue.Fields.Priority.Name {
	case "Low":
		colouredPriority = color.GreenString(issue.Fields.Priority.Name)
	case "Medium":
		colouredPriority = color.BlueString(issue.Fields.Priority.Name)
	case "High":
		colouredPriority = color.MagentaString(issue.Fields.Priority.Name)
	case "Critical":
	case "Blocker":
		colouredPriority = color.RedString(issue.Fields.Priority.Name)
	default:
		colouredPriority = color.GreenString(issue.Fields.Priority.Name)
	}
	var summary string
	if hasBranch {
		summary = fmt.Sprintf("*%s %v (%s): %+v", issue.Key, colouredPriority, issue.Fields.Type.Name, issue.Fields.Summary)
	} else {
		summary = fmt.Sprintf("%s %v (%s): %+v", issue.Key, colouredPriority, issue.Fields.Type.Name, issue.Fields.Summary)
	}
	return summary
}

// JiraKeyFromIssueSummary returns the Jira key from a summary generated by IssueSummary.
func JiraKeyFromIssueSummary(summary string) string {
	return strings.TrimPrefix(strings.Split(summary, " ")[0], "*")
}
